package content

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
	"testing"

	"github.com/nanolathe-gg/nanolathe/vfs"
)

// The map and battle-table read caps are host policy carried by a content
// profile (docs/DESIGN_CONTENT_VFS.md §5 "Content profiles"). These checks
// hold both halves at once: the retail baseline still refuses content larger
// than a retail install is sized for, with the overlay's own read-limit
// diagnostic, and a raised cap reads exactly the same content without changing
// how it is parsed.
//
// Both fixtures are generated here rather than committed: the point of the
// check is the size, and a multi-megabyte file in the repository would be a
// worse way to state it.

// oversizeFS serves one logical path from generated bytes that the fixture map
// does not hold, so a large file costs a single allocation and nothing on
// disk. It deliberately offers no ReadFileRange: a provider that can only hand
// back whole files is the case the read cap exists for, and it answers with
// vfs.ErrTooLarge exactly as the overlay does.
type oversizeFS struct {
	*fixtureFS
	path string
	data []byte
}

func newOversizeFS(inner *fixtureFS, path string, data []byte) *oversizeFS {
	return &oversizeFS{fixtureFS: inner, path: strings.ToLower(path), data: data}
}

func (f *oversizeFS) ReadFileLimit(name string, max int64) ([]byte, error) {
	if strings.ToLower(name) != f.path {
		return f.fixtureFS.ReadFileLimit(name, max)
	}
	if int64(len(f.data)) > max {
		return nil, fmt.Errorf("%s: %d bytes: %w", f.path, len(f.data), vfs.ErrTooLarge)
	}
	return f.data, nil
}

func (f *oversizeFS) Stat(name string) (vfs.EntryInfo, error) {
	if strings.ToLower(name) != f.path {
		return f.fixtureFS.Stat(name)
	}
	return vfs.EntryInfo{Path: f.path, Name: f.path, Size: int64(len(f.data))}, nil
}

// bigTerrainFixture is a TNT whose header is valid and whose body is padding,
// sized past the retail map read cap. Only the first sixty-four bytes are
// read; the padding exists to make the file large.
func bigTerrainFixture(size int) []byte {
	data := make([]byte, size)
	binary.LittleEndian.PutUint32(data, 0x2000)
	binary.LittleEndian.PutUint32(data[4:], 64)
	binary.LittleEndian.PutUint32(data[8:], 32)
	return data
}

// TestMapReadCapIsProfileData reads the same oversize terrain file twice: the
// retail cap refuses it and a profile's raised cap admits it, with the same
// compiled header either way.
func TestMapReadCapIsProfileData(t *testing.T) {
	const oversize = 17 << 20 // past the 16 MiB retail cap
	inner := newFixtureFS(t,
		fixtureFile{path: "maps/wide.ota", data: "[GlobalHeader] { [Schema 0] { Type=Network 1; } }"},
		fixtureFile{path: "maps/wide.tnt", data: "placeholder"},
	)
	fs := newOversizeFS(inner, "maps/wide.tnt", bigTerrainFixture(oversize))

	_, _, err := compileMapsWithDiagnostics(fs, RetailLimits(), nil)
	if err == nil {
		t.Fatal("the retail map read cap admitted a file larger than a retail install is sized for")
	}
	if !errors.Is(err, vfs.ErrTooLarge) {
		t.Fatalf("map read cap error = %v, want the overlay's read-limit error", err)
	}
	if !strings.Contains(err.Error(), "maps/wide.tnt") {
		t.Fatalf("map read cap error %q does not name the file", err)
	}

	raised := RetailLimits()
	raised.TNTBytes = 64 << 20
	maps, _, err := compileMapsWithDiagnostics(fs, raised, nil)
	if err != nil {
		t.Fatalf("raised map read cap: %v", err)
	}
	header := maps["wide"]
	if header == nil {
		t.Fatal("the raised cap read the file but compiled no map header")
	}
	if header.TNTWidth != 64 || header.TNTHeight != 32 {
		t.Fatalf("compiled header = %dx%d, want the authored 64x32", header.TNTWidth, header.TNTHeight)
	}
}

// TestMapReadCapDefaultsToRetail states that a zero cap is the retail cap, not
// an unbounded read: a profile that leaves the count unset must admit exactly
// what a retail install admits.
func TestMapReadCapDefaultsToRetail(t *testing.T) {
	limits, err := Limits{}.normalize()
	if err != nil {
		t.Fatalf("normalize: %v", err)
	}
	if limits.TNTBytes != RetailTNTBytes || limits.LOSBytes != RetailLOSBytes {
		t.Fatalf("unset caps normalized to %d/%d, want the retail %d/%d", limits.TNTBytes, limits.LOSBytes, RetailTNTBytes, RetailLOSBytes)
	}
}

// bigLOSFixture authors a LOS table file with the given table count, each
// table carrying lines wide enough to push the file past the retail
// battle-table read cap. Table n is authored as radius n: its one line is the
// point count followed by that many (0, k) pairs, the shape [03 R-VIS-01 §3]
// describes.
func bigLOSFixture(tables int, padTo int) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "[TABLEINFO]\n{\n\tnumtables=%d;\n}\n", tables)
	for n := 1; n <= tables; n++ {
		fmt.Fprintf(&b, "[TABLE%d]\n{\n\tnumlines=1;\n\tline1=%d", n, n)
		for k := 1; k <= n; k++ {
			fmt.Fprintf(&b, ", 0, %d", k)
		}
		b.WriteString(";\n}\n")
	}
	// Comment padding: the parser blanks comments before the grammar runs, so
	// the padding changes the file's size and nothing else [02 §4].
	for b.Len() < padTo {
		b.WriteString("// padding to size the file past the read cap\n")
	}
	return []byte(b.String())
}

// TestLOSReadCapIsProfileDataAndLargeTablesCompile is the E3 statement for the
// battle tables: the retail cap refuses a LOS file larger than a retail
// install's, a profile's raised cap reads it, and the compile then materializes
// every one of its ninety declared slots by the loader's own naming rule
// [03 R-COMP-02 §1]. Nothing in the compiled shape is bounded by a slot count:
// the retail loader sizes its table list to the declared numtables, so a
// ninety-table file is read the way a nine-table one is.
func TestLOSReadCapIsProfileDataAndLargeTablesCompile(t *testing.T) {
	const tables = 90
	body := bigLOSFixture(tables, 1<<20+4096) // past the 1 MiB retail cap
	inner := newFixtureFS(t, fixtureFile{path: "gamedata/los.tdf", data: "placeholder"})
	fs := newOversizeFS(inner, "gamedata/los.tdf", body)

	_, err := CompileLOSTables(fs, RetailLimits())
	if err == nil {
		t.Fatal("the retail battle-table read cap admitted a file larger than a retail install is sized for")
	}
	if !errors.Is(err, vfs.ErrTooLarge) {
		t.Fatalf("LOS read cap error = %v, want the overlay's read-limit error", err)
	}
	if !strings.Contains(err.Error(), "gamedata/los.tdf") {
		t.Fatalf("LOS read cap error %q does not name the file", err)
	}

	raised := RetailLimits()
	raised.LOSBytes = 8 << 20
	lt, err := CompileLOSTables(fs, raised)
	if err != nil {
		t.Fatalf("raised battle-table read cap: %v", err)
	}
	if lt.NumTables != tables {
		t.Fatalf("numtables = %d, want the declared %d", lt.NumTables, tables)
	}
	if len(lt.Tables) != tables {
		t.Fatalf("compiled %d tables, want one per declared slot", len(lt.Tables))
	}
	// Slot d holds TABLE d+1, and table n carries n points on its single line.
	for slot := 0; slot < tables; slot++ {
		table := lt.Tables[slot]
		if table.TableNum != slot+1 {
			t.Fatalf("slot %d holds TABLE%d, want TABLE%d", slot, table.TableNum, slot+1)
		}
		if len(table.Lines) != 1 {
			t.Fatalf("TABLE%d compiled %d lines, want one", table.TableNum, len(table.Lines))
		}
		line := table.Lines[0]
		if len(line) != 1+2*(slot+1) || int(line[0]) != slot+1 {
			t.Fatalf("TABLE%d line = %v, want a point count of %d followed by that many pairs", table.TableNum, line, slot+1)
		}
		if line[len(line)-1] != int32(slot+1) {
			t.Fatalf("TABLE%d last offset = %d, want the authored %d", table.TableNum, line[len(line)-1], slot+1)
		}
	}
}

// TestMeteorReadCapSharesTheBattleTableCap records that the meteor defaults
// are read under the same cap as the LOS table, so a content set that raises
// one raises both.
func TestMeteorReadCapSharesTheBattleTableCap(t *testing.T) {
	body := append([]byte("[Default]\n{\n\tMeteorWeapon=rock;\n\tMeteorRadius=5;\n\tMeteorDensity=1;\n\tMeteorDuration=2;\n\tMeteorInterval=3;\n}\n"), make([]byte, 1<<20)...)
	for i := len("[Default]\n{\n\tMeteorWeapon=rock;\n\tMeteorRadius=5;\n\tMeteorDensity=1;\n\tMeteorDuration=2;\n\tMeteorInterval=3;\n}\n"); i < len(body); i++ {
		body[i] = ' '
	}
	inner := newFixtureFS(t, fixtureFile{path: "gamedata/meteor.tdf", data: "placeholder"})
	fs := newOversizeFS(inner, "gamedata/meteor.tdf", body)

	if _, err := CompileMeteor(fs, RetailLimits()); !errors.Is(err, vfs.ErrTooLarge) {
		t.Fatalf("retail battle-table cap on meteor.tdf = %v, want the overlay's read-limit error", err)
	}
	raised := RetailLimits()
	raised.LOSBytes = 8 << 20
	md, err := CompileMeteor(fs, raised)
	if err != nil {
		t.Fatalf("raised battle-table read cap: %v", err)
	}
	if !md.DefaultPresent || md.MeteorWeapon != "rock" || md.MeteorRadius != 5 {
		t.Fatalf("compiled meteor defaults = %+v, want the authored block", md)
	}
}
