//go:build retail

package chrome

import (
	"bytes"
	"fmt"
	"go/format"
	"image"
	"image/png"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/nanolathe-gg/nanolathe/formats"
	retailpalette "github.com/nanolathe-gg/nanolathe/internal/palette"
	"github.com/nanolathe-gg/nanolathe/internal/testsupport"
	"github.com/nanolathe-gg/nanolathe/vfs"
)

// stockBanks are the banks whose covered entries the stock table names.
var stockBanks = []string{"anims/commongui.gaf", "anims/armint.gaf", "anims/corint.gaf"}

// keepStock names stock entries that have no gunmetal design: Core's top strip
// is 511 columns with its own layout, unlike the Arm strip TopBar draws.
var keepStock = map[string]bool{"anims/corint.gaf PANELTOP": true}

func retailInstall(t *testing.T) (*vfs.FS, [256][3]uint8) {
	t.Helper()
	fs := vfs.New()
	if err := fs.MountGameDirectory(testsupport.RetailRoot(t)); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { fs.Close() })
	tables, err := retailpalette.Load(fs)
	if err != nil {
		t.Fatal(err)
	}
	var pal [256][3]uint8
	for i := range pal {
		r, g, b, _ := tables.RGBA(byte(i))
		pal[i] = [3]uint8{r, g, b}
	}
	return fs, pal
}

// Every covered stock frame of the install is in the table under its own entry
// and index, so the stock art takes the gunmetal design and nothing else does.
// NANOLATHE_CHROME_WRITE_TABLE=1 regenerates stock_table.go from the install.
func TestStockTableCoversTheInstall(t *testing.T) {
	fs, _ := retailInstall(t)
	type row struct {
		hash string
		f    stockFrame
	}
	var rows []row
	for _, path := range stockBanks {
		bank, err := formats.LoadGAFFile(fs, path)
		if err != nil {
			t.Fatalf("%s: %v", path, err)
		}
		for _, entry := range bank.Entries {
			if _, ok := lookup(entry.Name); !ok {
				continue
			}
			for i, ref := range entry.Frames {
				if !plainFrame(ref.Frame) {
					continue
				}
				rows = append(rows, row{FrameHash(ref.Frame), stockFrame{entry.Name, i, keepStock[path+" "+entry.Name]}})
			}
		}
	}
	if os.Getenv("NANOLATHE_CHROME_WRITE_TABLE") != "" {
		sort.Slice(rows, func(a, b int) bool {
			if rows[a].f.name != rows[b].f.name {
				return rows[a].f.name < rows[b].f.name
			}
			return rows[a].f.frame < rows[b].f.frame
		})
		var b strings.Builder
		b.WriteString("// Code generated by TestStockTableCoversTheInstall; DO NOT EDIT.\n\npackage chrome\n\n")
		b.WriteString("// stockFrames identifies the stock interface frames by FrameHash.\nvar stockFrames = map[string]stockFrame{\n")
		for _, r := range rows {
			fmt.Fprintf(&b, "\t%q: {%q, %d, %t},\n", r.hash, r.f.name, r.f.frame, r.f.keep)
		}
		b.WriteString("}\n")
		src, err := format.Source([]byte(b.String()))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile("stock_table.go", src, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	for _, r := range rows {
		if got, ok := stockFrames[r.hash]; !ok || got != r.f {
			t.Errorf("%s frame %d: table has %+v (present %t)", r.f.name, r.f.frame, got, ok)
		}
	}
}

// NANOLATHE_CHROME_PREVIEW=<dir> writes every remastered stock frame beside
// its nearest-doubled original, for looking at.
func TestPreviewStockRemaster(t *testing.T) {
	dir := os.Getenv("NANOLATHE_CHROME_PREVIEW")
	if dir == "" {
		t.Skip("set NANOLATHE_CHROME_PREVIEW to write previews")
	}
	fs, pal := retailInstall(t)
	for _, path := range stockBanks {
		bank, err := formats.LoadGAFFile(fs, path)
		if err != nil {
			t.Fatal(err)
		}
		out, err := Bank2x(bank, pal, Options{})
		if err != nil {
			t.Fatal(err)
		}
		for i, entry := range out.Entries {
			for j, ref := range entry.Frames {
				if ref.Frame == nil {
					continue
				}
				src := bank.Entries[i].Frames[j].Frame.Doubled()
				name := fmt.Sprintf("%s-%s-%d.png", strings.TrimSuffix(filepath.Base(path), ".gaf"), entry.Name, j)
				writePair(t, filepath.Join(dir, name), src, ref.Frame, pal)
			}
		}
	}
}

func writePair(t *testing.T, path string, a, b *formats.GAFFrame, pal [256][3]uint8) {
	t.Helper()
	w := int(a.Width) + 4 + int(b.Width)
	h := max(int(a.Height), int(b.Height))
	img := image.NewNRGBA(image.Rect(0, 0, w, h))
	put := func(f *formats.GAFFrame, ox int) {
		for y := range int(f.Height) {
			for x := range int(f.Width) {
				i := y*int(f.Width) + x
				if f.Transparent[i] {
					continue
				}
				c := pal[f.Pixels[i]]
				o := img.PixOffset(ox+x, y)
				copy(img.Pix[o:], []byte{c[0], c[1], c[2], 255})
			}
		}
	}
	put(a, 0)
	put(b, int(a.Width)+4)
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		t.Fatal(err)
	}
}
