package cleanroom

// Baseline is the census of raw-forensics occurrences that predate the
// clean-room lint, taken with tools/cleanroom-baseline. It is a debt
// register, not a permission list: every entry is a comment or research
// line that still has to be rewritten as clean-room prose, with its
// address-level trail moved to /tmp/ta-decompile/notes/.
//
// Total at baseline: 561 occurrences across 67 files.
//
// A file absent from this map must have zero occurrences. Counts may only
// go down, and going down requires updating this file in the same change.
var Baseline = map[string]int{
	"cmd/nanolathe/allies_test.go":                  1,
	"cmd/nanolathe/selmap_test.go":                  3,
	"formats/gaf_colorkey_test.go":                  2,
	"internal/ai/o6_score_test.go":                  5,
	"internal/audio/player.go":                      1,
	"internal/audio/positional.go":                  1,
	"internal/cob/ports.go":                         7,
	"internal/cob/ports_test.go":                    3,
	"internal/cob/vm.go":                            98,
	"internal/combat/aim.go":                        1,
	"internal/combat/damage.go":                     7,
	"internal/combat/death.go":                      2,
	"internal/combat/impact.go":                     1,
	"internal/combat/meteor.go":                     1,
	"internal/combat/motion.go":                     6,
	"internal/combat/motion_test.go":                1,
	"internal/combat/pool.go":                       20,
	"internal/combat/slots.go":                      44,
	"internal/combat/stockpile.go":                  13,
	"internal/combat/target.go":                     9,
	"internal/construction/capture.go":              22,
	"internal/construction/factory_test.go":         1,
	"internal/construction/gap_p014_p015_test.go":   2,
	"internal/construction/resurrection.go":         24,
	"internal/construction/reverse.go":              6,
	"internal/construction/rs10_test.go":            1,
	"internal/content/ai_profile.go":                1,
	"internal/content/sound_sc7_test.go":            1,
	"internal/features/reproduce.go":                1,
	"internal/features/sink.go":                     2,
	"internal/hud/cursor.go":                        1,
	"internal/hud/minimap_test.go":                  7,
	"internal/hud/selection_test.go":                2,
	"internal/mission/catalog.go":                   1,
	"internal/mission/initial_mission.go":           5,
	"internal/mission/placement.go":                 18,
	"internal/mission/sparse_test.go":               1,
	"internal/movement/collision.go":                13,
	"internal/movement/flight.go":                   5,
	"internal/movement/integrate.go":                13,
	"internal/movement/locomotion_fidelity_test.go": 4,
	"internal/movement/profile.go":                  9,
	"internal/movement/steer.go":                    71,
	"internal/movement/transport.go":                1,
	"internal/orders/pump_test.go":                  2,
	"internal/orders/resolve.go":                    1,
	"internal/orders/selectable.go":                 1,
	"internal/orders/zbuildweapon.go":               6,
	"internal/render/minimap_test.go":               2,
	"internal/render/model_test.go":                 1,
	"internal/save/bank_test.go":                    1,
	"internal/save/retail_corpus_test.go":           1,
	"internal/session/skirmish.go":                  2,
	"internal/settings/settings.go":                 10,
	"internal/settings/settings_test.go":            1,
	"internal/units/sweep.go":                       4,
	"internal/visibility/fog.go":                    1,
	"internal/world/picking.go":                     1,
	"internal/world/placement.go":                   2,
	"internal/world/placement_test.go":              2,
	"internal/world/plot.go":                        57,
	"internal/world/terrain.go":                     5,
	"internal/world/terrain_test.go":                2,
}
