package cleanroom

// Baseline is the census of raw-forensics occurrences that predate the
// clean-room lint, taken with tools/cleanroom-baseline. It is a debt
// register, not a permission list: every entry is a comment or research
// line that still has to be rewritten as clean-room prose, with its
// address-level trail moved to /tmp/ta-decompile/notes/.
//
// Total at baseline: 1408 occurrences across 116 files.
//
// A file absent from this map must have zero occurrences. Counts may only
// go down, and going down requires updating this file in the same change.
var Baseline = map[string]int{
	"cmd/nanolathe/allies_test.go":                  1,
	"cmd/nanolathe/battle_controller.go":            1,
	"cmd/nanolathe/frontend.go":                     18,
	"cmd/nanolathe/loading.go":                      16,
	"cmd/nanolathe/loading_test.go":                 1,
	"cmd/nanolathe/retail_font.go":                  17,
	"cmd/nanolathe/retail_font_test.go":             3,
	"cmd/nanolathe/retail_menu.go":                  57,
	"cmd/nanolathe/selmap_test.go":                  3,
	"cmd/nanolathe/settings.go":                     3,
	"formats/gaf_colorkey_test.go":                  2,
	"internal/ai/groups.go":                         12,
	"internal/ai/groups_test.go":                    2,
	"internal/ai/manager.go":                        69,
	"internal/ai/o6_score_test.go":                  5,
	"internal/ai/placement.go":                      22,
	"internal/ai/placement_test.go":                 1,
	"internal/ai/profile.go":                        7,
	"internal/ai/selection.go":                      10,
	"internal/ai/strategic.go":                      79,
	"internal/ai/strategic_test.go":                 3,
	"internal/audio/player.go":                      1,
	"internal/audio/positional.go":                  1,
	"internal/camera/camera.go":                     2,
	"internal/camera/minimap.go":                    29,
	"internal/camera/minimap_test.go":               16,
	"internal/client/minimap_draw_test.go":          2,
	"internal/client/unitdraw.go":                   9,
	"internal/clock/clock.go":                       11,
	"internal/cob/ports.go":                         8,
	"internal/cob/ports_test.go":                    3,
	"internal/cob/vm.go":                            104,
	"internal/combat/aim.go":                        1,
	"internal/combat/damage.go":                     7,
	"internal/combat/death.go":                      2,
	"internal/combat/impact.go":                     1,
	"internal/combat/meteor.go":                     1,
	"internal/combat/motion.go":                     6,
	"internal/combat/motion_test.go":                1,
	"internal/combat/pool.go":                       20,
	"internal/combat/slots.go":                      44,
	"internal/combat/stockpile.go":                  13,
	"internal/combat/target.go":                     9,
	"internal/construction/capture.go":              22,
	"internal/construction/factory_test.go":         1,
	"internal/construction/gap_p014_p015_test.go":   2,
	"internal/construction/resurrection.go":         28,
	"internal/construction/reverse.go":              6,
	"internal/construction/rs10_test.go":            1,
	"internal/content/ai_profile.go":                1,
	"internal/content/catalog.go":                   6,
	"internal/content/compile_feature.go":           4,
	"internal/content/compile_map.go":               1,
	"internal/content/compile_movement.go":          35,
	"internal/content/compile_unit.go":              11,
	"internal/content/movement_sc5_test.go":         17,
	"internal/content/ovr.go":                       16,
	"internal/content/sound_sc7_test.go":            2,
	"internal/economy/admission.go":                 1,
	"internal/economy/gap_p106_test.go":             7,
	"internal/economy/ledger.go":                    44,
	"internal/economy/maker.go":                     13,
	"internal/economy/tick.go":                      12,
	"internal/features/reproduce.go":                1,
	"internal/features/sink.go":                     2,
	"internal/hud/cursor.go":                        1,
	"internal/hud/minimap_test.go":                  7,
	"internal/hud/selection_test.go":                2,
	"internal/mission/catalog.go":                   1,
	"internal/mission/initial_mission.go":           6,
	"internal/mission/mission_globals.go":           135,
	"internal/mission/placement.go":                 18,
	"internal/mission/sparse_test.go":               1,
	"internal/movement/collision.go":                13,
	"internal/movement/flight.go":                   5,
	"internal/movement/integrate.go":                24,
	"internal/movement/locomotion_fidelity_test.go": 4,
	"internal/movement/profile.go":                  9,
	"internal/movement/steer.go":                    71,
	"internal/movement/transport.go":                1,
	"internal/orders/pump_test.go":                  4,
	"internal/orders/resolve.go":                    1,
	"internal/orders/selectable.go":                 1,
	"internal/orders/zbuildweapon.go":               6,
	"internal/path/queue.go":                        1,
	"internal/pool/pool.go":                         40,
	"internal/pool/pool_test.go":                    6,
	"internal/render/minimap_test.go":               2,
	"internal/render/model_test.go":                 1,
	"internal/save/bank_test.go":                    1,
	"internal/save/retail_corpus_test.go":           1,
	"internal/session/battle_entry_test.go":         6,
	"internal/session/composition.go":               7,
	"internal/session/economy.go":                   4,
	"internal/session/los_emitter_test.go":          4,
	"internal/session/skirmish.go":                  2,
	"internal/session/strict_g2_move_test.go":       2,
	"internal/settings/settings.go":                 10,
	"internal/settings/settings_test.go":            1,
	"internal/triggers/eval.go":                     10,
	"internal/triggers/triggers.go":                 2,
	"internal/units/pipeline.go":                    10,
	"internal/units/status_lifecycle_test.go":       1,
	"internal/units/sweep.go":                       4,
	"internal/units/types.go":                       11,
	"internal/units/units.go":                       42,
	"internal/units/units_test.go":                  2,
	"internal/visibility/fog.go":                    1,
	"internal/visibility/grids.go":                  1,
	"internal/visibility/sensors_test.go":           1,
	"internal/world/picking.go":                     1,
	"internal/world/placement.go":                   2,
	"internal/world/placement_test.go":              2,
	"internal/world/plot.go":                        57,
	"internal/world/terrain.go":                     5,
	"internal/world/terrain_test.go":                2,
}
