package main

import (
	"fmt"
	"math"
	"sync/atomic"

	"github.com/nanolathe/nanolathe/formats"
	"github.com/nanolathe/nanolathe/internal/client"
	"github.com/nanolathe/nanolathe/internal/content"
	"github.com/nanolathe/nanolathe/internal/session"
)

// The loading screen uses the logical 640x480 surface, draws
// bitmaps/loadgame2bg.pcx as a full-screen background, starts loading on a
// separate worker, and repaints while that worker runs [07 "The loading screen"].
const (
	retailLoadStages = 6
	// Six authored rows. Each label is at x=0x5a and each bar at x=0xcd; row Y
	// positions are authored individually rather than generated by a step
	// [07 "The loading screen"].
	retailLoadLabelX = 0x5a
	retailLoadBarX   = 0xcd
	// The bar is filled to left + progress*7/2 and is inclusive of its right
	// and bottom edges, so a full bar is 351 wide — exactly the LIGHTBAR frame
	// that is stamped over it.
	retailLoadBarBottom = 20
	// A stage's flash counter is set to 30 on the repaint that first sees 100%
	// and every non-zero counter drops by two per repaint. The counter is the
	// shade level handed to the glyph blitter [07 "The loading screen"].
	retailLoadFlashStart = 30
	retailLoadFlashStep  = 2
	// The retail loader sleeps 200 ms at the end of every repaint, putting the
	// screen at five repaints a second and the flash decay at fifteen repaints,
	// or three seconds. Nanolathe
	// runs its loader as a goroutine the runtime schedules against the
	// renderer, so the screen is painted at the display rate instead and only
	// the flash is stepped on retail's cadence. Deliberate divergence: the
	// bars move more smoothly than retail's, and nothing else changes.
	retailLoadRepaintSeconds = 0.2
	// The GUI semantic color fields the screen draws with. They are read from
	// the GUI context's nearest-color map, so semantic GUI colors 10, 12, and
	// 15 are resolved through the active display palette [03 §4.3].
	retailLoadDoneColor    = 10
	retailLoadWorkingColor = 12
	retailLoadTitleColor   = 15
)

// retailLoadBars are the authored rows, in order. The labels and Y values are
// the loading-screen contract [07 "The loading screen"].
var retailLoadBars = [retailLoadStages]struct {
	label string
	y     int
}{
	{"Textures", 0x87},
	{"Terrain", 0xb1},
	{"Units", 0xda},
	{"Animation", 0x106},
	{"3D Data", 0x130},
	{"Explosions", 0x15b},
}

// retailLoadStageOf maps one Nanolathe load family onto one of the six retail
// bars.
//
// Deliberate divergence: the screen, its six labels and their geometry are
// retail's, but the attribution is ours, because Nanolathe's loaders are not
// TotalA.exe's. Retail's six bars are fed by six separate loaders — tile
// textures, TNT terrain, unit definitions, GAF animation, 3DO data and the
// explosion/weapon tables. Nanolathe compiles one immutable catalog instead,
// so each bar is driven by the families closest in kind: COB scripts stand in
// for animation because unit animation in TA is the COB VM, the model catalog
// stands in for 3D data, and weapons and features stand in for explosions.
// Textures carries the interface data the client presents. Re-attribute this
// when the renderer grows real texture and animation load steps.
//
// Retail's own six curves are Established and are not reproducible here,
// because they are each loader's own division [07 "The loading screen"]: the
// texture bar walks the texture directory writing `index * 100 / (count - 1)`;
// the terrain bar reads the map file in ten equal chunks and steps 9, 18, …, 90,
// reaching 100 only when world setup finishes; the unit bar writes
// `index * 100 / unitCount` and then 100; the animation bar writes
// `index * 100 / entryCount` and **never writes 100**, so that one label's
// completion flash never fires; the 3D-data bar divides one past the live page
// index by the live count, so its last in-loop write overshoots 100 before the
// final 100 lands; and the explosion bar is three flat milestones — 20, 50,
// 100 — one per precomputed explosion table. The weighted attribution below is
// ours; only the six labels, their geometry and the completion flash are
// retail's.
var retailLoadStageOf = map[string]int{
	content.FamilySides:        0,
	content.FamilySounds:       0,
	content.FamilyBuildMenus:   0,
	content.FamilyMaps:         1,
	session.FamilyTerrain:      1,
	content.FamilyUnits:        2,
	content.FamilyMovement:     2,
	content.FamilyAIProfiles:   2,
	content.FamilyBattleTables: 2,
	session.FamilyUnitWorld:    2,
	session.FamilyPlacement:    3,
	session.FamilyScripts:      3,
	content.FamilyModels:       4,
	content.FamilyWeapons:      5,
	content.FamilyFeatures:     5,
}

// retailLoadStageWeight is how many families feed each bar, so a bar can show
// its own families completing one at a time.
var retailLoadStageWeight = func() (w [retailLoadStages]int) {
	// Counting into a fixed array: the result does not depend on map order.
	for _, stage := range retailLoadStageOf {
		w[stage]++
	}
	return
}()

type loadResult struct {
	sess *session.Session
	err  error
}

// loadingState is the model behind the loading screen. The loader runs on its
// own goroutine, as retail's does on its own thread, so percent is read by the
// renderer while the loader writes it; nothing else crosses.
type loadingState struct {
	// mapName is empty for a campaign mission, whose loading screen omits the
	// map line [07 "The loading screen"].
	mapName string
	percent [retailLoadStages]atomic.Int32
	family  map[string]int32
	done    chan loadResult

	// Renderer-side only.
	flash   [retailLoadStages]int
	prev    [retailLoadStages]int
	repaint float64
}

func newLoadingState(mapName string) *loadingState {
	return &loadingState{
		mapName: mapName,
		family:  make(map[string]int32, len(retailLoadStageOf)),
		done:    make(chan loadResult, 1),
	}
}

// advanceFlash is one retail repaint's worth of flash bookkeeping: arm a stage
// that has just reached 100, otherwise decay whatever is already armed.
func (l *loadingState) advanceFlash() {
	for i := range l.percent {
		percent := int(l.percent[i].Load())
		switch {
		case percent >= 100 && l.prev[i] < 100:
			l.flash[i] = retailLoadFlashStart
		case l.flash[i] > 0:
			l.flash[i] -= retailLoadFlashStep
			if l.flash[i] < 0 {
				l.flash[i] = 0
			}
		}
		l.prev[i] = percent
	}
}

// report is the content.Progress the loader is given. It recomputes the bar
// its family belongs to as the mean of that bar's families, which is what
// lets a bar fed by several small catalogs rise in steps.
func (l *loadingState) report(family string, percent int) {
	stage, ok := retailLoadStageOf[family]
	if !ok {
		return
	}
	l.family[family] = int32(percent)
	total := int32(0)
	// Integer sum over the bar's families: the result does not depend on map
	// order, so this traversal stays deterministic [INVARIANTS I1].
	for name, value := range l.family {
		if retailLoadStageOf[name] == stage {
			total += value
		}
	}
	weight := int32(retailLoadStageWeight[stage])
	if weight < 1 {
		weight = 1
	}
	l.percent[stage].Store(total / weight)
}

// startBattleLoad puts the shell on the loading screen and hands the work to a
// goroutine, matching the loading screen's separate worker. The session is
// adopted only on the render goroutine, in step [07 "The loading screen"].
func (g *gameShell) startBattleLoad(mapName string) {
	// Start is the commit point for the skirmish setup: the next run of the
	// engine opens SKIRMISH.GUI on the rows this battle was started with.
	g.saveSettings()
	cfg := g.skirmishConfigForStart(mapName)
	request, err := skirmishBattleRequest(g.opts, g.cs, cfg, headlessScenarioSkirmish, nil, newBattleSeedSource(g.opts))
	if err != nil {
		reportRetailMessageError(g.showRetailMessage(err.Error()))
		return
	}
	g.beginFreshBattleLoad(mapName, modeMenuSkirmish, request, nil)
	// The request above is the sole owner of constructor selection and seeds;
	// the loading worker only invokes the shared authoritative seam [08
	// R-ENTRY-01 §1–§2].
}

// startMissionLoad is the campaign entry. Retail shows the same screen with
// the same six bars; only the map line is gated off for a mission.
func (g *gameShell) startMissionLoad() {
	if g.campaignIdx < 0 || g.campaignIdx >= len(g.campaignOptions) {
		reportRetailMessageError(g.showRetailMessage("no campaign selected"))
		return
	}
	c := g.campaignOptions[g.campaignIdx]
	if g.missionIdx < 0 || g.missionIdx >= len(c.Missions) {
		reportRetailMessageError(g.showRetailMessage("no mission selected"))
		return
	}
	path := fmt.Sprintf("%s:MISSION%d", c.Path, c.Missions[g.missionIdx].Index)
	difficulty := g.missionDifficulty()
	missionIndex := c.Missions[g.missionIdx].Index
	campaignSlot := g.missionIdx
	g.saveSettings()
	request, err := missionBattleRequest(g.opts, g.cs, path, difficulty, missionIndex, campaignSlot, nil, newBattleSeedSource(g.opts))
	if err != nil {
		reportRetailMessageError(g.showRetailMessage(err.Error()))
		return
	}
	g.beginFreshBattleLoad("", modeMenuMission, request, nil)
}

// loadRetailSavePath is the explicit production save-file seam. It is called
// on the render thread by a host/UI integration that already selected a path;
// no file-picker policy is invented here. The session package prepares all
// authoritative state detached, and this method commits only after battle
// presentation composition has also succeeded [08 R-SAVE-02 §11–§12].
func (g *gameShell) loadRetailSavePath(path string) error {
	if g == nil || g.cs == nil || g.cs.fs == nil {
		return fmt.Errorf("nanolathe: retail save load requires mounted content")
	}
	sim, crt := seedsFor(g.opts)
	// A restored non-campaign battle sizes its unit pool from the configured
	// `[Preferences] UnitLimit`, as a fresh skirmish does [05 R-SHARE-01 §7].
	loaded, err := session.LoadRetailSavePath(path, session.RetailLoadDeps{
		FS: g.cs.fs, SimSeed: sim, CRTSeed: crt, UnitLimit: g.setup.UnitLimit,
	})
	if err != nil {
		return err
	}
	if loaded.Route == session.RetailLoadRouteCampaignContinuation {
		return g.applyRetailContinuation(loaded.Continuation)
	}
	if loaded.Battle == nil || loaded.Battle.Session == nil || loaded.Battle.Image == nil {
		return fmt.Errorf("nanolathe: retail save load returned no battle candidate")
	}
	sess := loaded.Battle.Session
	if g.audioOwner != nil {
		sess.Audio = g.audioOwner
	}
	battle, err := composeBattleEntryDetached(sess, sess.Catalog, g.cs, g, &loaded.Battle.Image.Camera)
	if err != nil {
		return err
	}
	// The only mutation of the active battle/frontend/client state occurs here,
	// after both authoritative and presentation candidates are complete.
	g.commitBattleCandidate(battle)
	return nil
}

func (g *gameShell) beginFreshBattleLoad(mapName string, back shellMode, request freshBattleRequest, after func(*session.Session)) {
	g.teardownBattle(clPtr)
	g.bindFrontendClient(clPtr)
	state := newLoadingState(mapName)
	request.value.Progress = state.report
	g.loading = state
	g.loadingReturn = back
	g.openMenu(modeLoading)
	// The skirmish and campaign load transitions compare
	// `DisplaymodeWidth`/`Height` to the current window size and, when they
	// differ, resize the window, re-select the mode and re-create the
	// offscreen [07 R-FE-01 §11]. This is that transition: the front end runs
	// at 640x480 whatever the pair holds [07 R-FE-02 §2], and the battle about
	// to be composed runs at the chosen mode.
	g.applyDisplayMode(clPtr)
	go func() {
		authoritative, err := composeAuthoritativeBattle(request)
		if err == nil && after != nil {
			after(authoritative.Session)
		}
		state.done <- loadResult{sess: authoritative.Session, err: err}
	}()
}

// stepLoading advances the flash on retail's repaint cadence and adopts the
// finished session, or reports the failure the way the screen it was reached
// from reports any other start error.
func (g *gameShell) stepLoading(delta float64) {
	l := g.loading
	if l == nil {
		g.openMenu(g.loadingReturn)
		return
	}
	for l.repaint += delta; l.repaint >= retailLoadRepaintSeconds; l.repaint -= retailLoadRepaintSeconds {
		l.advanceFlash()
	}
	select {
	case res := <-l.done:
		returnMode := g.loadingReturn
		g.loading = nil
		if res.err != nil {
			g.openMenu(returnMode)
			reportRetailMessageError(g.showRetailMessage(res.err.Error()))
			return
		}
		if err := g.enterBattle(res.sess, res.sess.Catalog); err != nil {
			g.loadingReturn = returnMode
			g.openMenu(returnMode)
			g.bindFrontendClient(clPtr)
			reportRetailMessageError(g.showRetailMessage(err.Error()))
		}
	default:
	}
}

func (g *gameShell) drawLoadingScreen(c *client.Client) {
	l := g.loading
	if l == nil || g.assets == nil {
		return
	}
	if bg := g.assets.loading; bg != nil {
		c.UIBlitPCX(bg, 0, 0)
	}
	// The map line comes before the rows, and a campaign mission draws none
	// [07 "The loading screen"].
	if l.mapName != "" {
		title := fmt.Sprintf("%s: %s", "Map", l.mapName)
		width := g.retailTextWidth(title)
		screenW, screenH := c.Size()
		y := int(math.Trunc(float64(screenH) - float64(g.retailTextHeight())*1.5))
		g.drawRetailString(c, title, screenW/2-width/2, y, -1, g.guiColor(retailLoadTitleColor))
	}
	lightbar := g.retailLightBarFrame()
	for i := range retailLoadBars {
		percent := int(l.percent[i].Load())
		if percent < 0 {
			percent = 0
		}
		if percent > 100 {
			percent = 100
		}
		row := retailLoadBars[i]
		// The row's percentage selects one semantic color, which is shared by its
		// label and fill [07 "The loading screen"].
		fill := g.guiColor(retailLoadWorkingColor)
		if percent >= 100 {
			fill = g.guiColor(retailLoadDoneColor)
		}
		// Retail's order within a row is label, fill, grille. The label is at
		// x=0x5a and the bar at x=0xcd, so they never overlap, but keep the
		// order anyway.
		g.drawRetailStringLit(c, row.label, retailLoadLabelX, row.y, -1, fill, l.flash[i])
		// left..left+percent*7/2 inclusive, top..top+20 inclusive.
		c.UIFillRect(retailLoadBarX, row.y, percent*7/2+1, retailLoadBarBottom+1, fill)
		if lightbar != nil {
			blitRetailFrame(c, lightbar, retailLoadBarX, row.y)
		}
	}
}

// retailLightBarFrame is the common LIGHTBAR entry's frame 0: a 351x21 metal
// grille whose slots are transparent, so the filled part of the bar shows
// through it. The frame carries authored offsets of (19, -27). The
// loading-screen blit path subtracts frame offsets from the pen, so the
// offsets are zeroed before stamping or the grille would miss its bar.
// Nanolathe's gadget blit ignores GAF offsets already, which lands in the same
// place [fmt gaf][07 "The loading screen"].
func (g *gameShell) retailLightBarFrame() *formats.GAFFrame {
	if g == nil || g.assets == nil || g.assets.common == nil {
		return nil
	}
	e, ok := g.assets.common.Find("LIGHTBAR")
	if !ok || len(e.Frames) == 0 {
		return nil
	}
	return e.Frames[0].Frame
}
