package main

import (
	"fmt"
	"math"
	"sync/atomic"

	"github.com/nanolathe-gg/nanolathe/formats"
	"github.com/nanolathe-gg/nanolathe/internal/client"
	"github.com/nanolathe-gg/nanolathe/internal/content"
	"github.com/nanolathe-gg/nanolathe/internal/mission"
	"github.com/nanolathe-gg/nanolathe/internal/save"
	"github.com/nanolathe-gg/nanolathe/internal/session"
)

// The loading screen uses the logical 640x480 surface, draws
// bitmaps/loadgame2bg.pcx as a full-screen background, starts loading on a
// separate worker, and repaints while that worker runs [07 "The loading screen"].
const (
	retailLoadStages = 6
	// Six authored rows. Each label is at x=0x5a and each bar at x=0xcd; row Y
	// positions are authored individually rather than generated by a step
	// [07 "The loading screen"].
	retailLoadLabelX = 0x5a
	retailLoadBarX   = 0xcd
	// The bar is filled to left + progress*7/2 and is inclusive of its right
	// and bottom edges, so a full bar is 351 wide — exactly the LIGHTBAR frame
	// that is stamped over it.
	retailLoadBarBottom = 20
	// A stage's flash counter is set to 30 on the repaint that first sees 100%
	// and every non-zero counter drops by two per repaint. The counter is the
	// shade level handed to the glyph blitter [07 "The loading screen"].
	retailLoadFlashStart = 30
	retailLoadFlashStep  = 2
	// The retail loader sleeps 200 ms at the end of every repaint, putting the
	// screen at five repaints a second and the flash decay at fifteen repaints,
	// or three seconds. Nanolathe
	// runs its loader as a goroutine the runtime schedules against the
	// renderer, so the screen is painted at the display rate instead and only
	// the flash is stepped on retail's cadence. Deliberate divergence: the
	// bars move more smoothly than retail's, and nothing else changes.
	retailLoadRepaintSeconds = 0.2
	// The GUI semantic color fields the screen draws with. They are read from
	// the GUI context's nearest-color map, so semantic GUI colors 10, 12, and
	// 15 are resolved through the active display palette [03 §4.3].
	retailLoadDoneColor    = 10
	retailLoadWorkingColor = 12
	retailLoadTitleColor   = 15
)

// retailLoadBars are the authored rows, in order. The labels and Y values are
// the loading-screen contract [07 "The loading screen"].
var retailLoadBars = [retailLoadStages]struct {
	label string
	y     int
}{
	{"Textures", 0x87},
	{"Terrain", 0xb1},
	{"Units", 0xda},
	{"Animation", 0x106},
	{"3D Data", 0x130},
	{"Explosions", 0x15b},
}

// retailLoadStageOf maps one Nanolathe load family onto one of the six retail
// bars.
//
// Deliberate divergence: the screen, its six labels and their geometry are
// retail's, but the attribution is ours, because Nanolathe's loaders are not
// TotalA.exe's. Retail's six bars are fed by six separate loaders — tile
// textures, TNT terrain, unit definitions, GAF animation, 3DO data and the
// explosion/weapon tables. Nanolathe compiles one immutable catalog instead,
// so each bar is driven by the families closest in kind: COB scripts stand in
// for animation because unit animation in TA is the COB VM, the model catalog
// stands in for 3D data, and weapons and features stand in for explosions.
// Textures carries the interface data the client presents. Re-attribute this
// when the renderer grows real texture and animation load steps.
//
// Retail's own six curves are Established and are not reproducible here,
// because they are each loader's own division [07 "The loading screen"]: the
// texture bar walks the texture directory writing `index * 100 / (count - 1)`;
// the terrain bar reads the map file in ten equal chunks and steps 9, 18, …, 90,
// reaching 100 only when world setup finishes; the unit bar writes
// `index * 100 / unitCount` and then 100; the animation bar writes
// `index * 100 / entryCount` and **never writes 100**, so that one label's
// completion flash never fires; the 3D-data bar divides one past the live page
// index by the live count, so its last in-loop write overshoots 100 before the
// final 100 lands; and the explosion bar is three flat milestones — 20, 50,
// 100 — one per precomputed explosion table. The weighted attribution below is
// ours; only the six labels, their geometry and the completion flash are
// retail's.
var retailLoadStageOf = map[string]int{
	content.FamilySides:      0,
	content.FamilySounds:     0,
	content.FamilyBuildMenus: 0,
	content.FamilyMaps:       1,
	session.FamilyTerrain:    1,
	// The load-time remaster is map art and is reported on the terrain bar
	// (DESIGN_GPU_RENDERER §14.4 "When"). Every load that shows this screen
	// drives the family to 100 even when the remaster is off, because the bar
	// is the mean of its families.
	familyDetailArt:            1,
	content.FamilyUnits:        2,
	content.FamilyMovement:     2,
	content.FamilyAIProfiles:   2,
	content.FamilyBattleTables: 2,
	session.FamilyUnitWorld:    2,
	session.FamilyPlacement:    3,
	session.FamilyScripts:      3,
	content.FamilyModels:       4,
	content.FamilyWeapons:      5,
	content.FamilyFeatures:     5,
}

// retailLoadStageWeight is how many families feed each bar, so a bar can show
// its own families completing one at a time.
var retailLoadStageWeight = func() (w [retailLoadStages]int) {
	// Counting into a fixed array: the result does not depend on map order.
	for _, stage := range retailLoadStageOf {
		w[stage]++
	}
	return
}()

type loadResult struct {
	sess *session.Session
	err  error
	// detail is the load-time remaster's art for this map, synthesized on the
	// loader goroutine beside the session and installed at adoption
	// (DESIGN_GPU_RENDERER §14.4). Nil is "no provider": nearest doubling.
	detail *client.DetailArt
}

// loadingState is the model behind the loading screen. The loader runs on its
// own goroutine, as retail's does on its own thread, so percent is read by the
// renderer while the loader writes it. Remaster status crosses as an immutable
// snapshot; all elapsed-time bookkeeping belongs to the renderer.
type loadingState struct {
	// mapName is empty for a campaign mission, whose loading screen omits the
	// map line [07 "The loading screen"].
	mapName string
	percent [retailLoadStages]atomic.Int32
	family  map[string]int32
	done    chan loadResult

	remaster atomic.Pointer[remasterProgress]

	// Renderer-side only.
	remasterElapsed float64
	flash           [retailLoadStages]int
	prev            [retailLoadStages]int
	repaint         float64
}

func newLoadingState(mapName string) *loadingState {
	return &loadingState{
		mapName: mapName,
		family:  make(map[string]int32, len(retailLoadStageOf)),
		done:    make(chan loadResult, 1),
	}
}

// advanceFlash is one retail repaint's worth of flash bookkeeping: arm a stage
// that has just reached 100, otherwise decay whatever is already armed.
func (l *loadingState) advanceFlash() {
	for i := range l.percent {
		percent := int(l.percent[i].Load())
		switch {
		case percent >= 100 && l.prev[i] < 100:
			l.flash[i] = retailLoadFlashStart
		case l.flash[i] > 0:
			l.flash[i] -= retailLoadFlashStep
			if l.flash[i] < 0 {
				l.flash[i] = 0
			}
		}
		l.prev[i] = percent
	}
}

// report is the content.Progress the loader is given. It recomputes the bar
// its family belongs to as the mean of that bar's families, which is what
// lets a bar fed by several small catalogs rise in steps.
func (l *loadingState) report(family string, percent int) {
	if l.reportRemaster(family, percent) {
		return
	}
	stage, ok := retailLoadStageOf[family]
	if !ok {
		return
	}
	l.family[family] = int32(percent)
	total := int32(0)
	// Integer sum over the bar's families: the result does not depend on map
	// order, so this traversal stays deterministic [INVARIANTS I1].
	for name, value := range l.family {
		if retailLoadStageOf[name] == stage {
			total += value
		}
	}
	weight := int32(retailLoadStageWeight[stage])
	if weight < 1 {
		weight = 1
	}
	l.percent[stage].Store(total / weight)
}

// startBattleLoad puts the shell on the loading screen and hands the work to a
// goroutine, matching the loading screen's separate worker. The session is
// adopted only on the render goroutine, in step [07 "The loading screen"].
func (g *gameShell) startBattleLoad(mapName string) {
	// Start is the commit point for the skirmish setup: the next run of the
	// engine opens SKIRMISH.GUI on the rows this battle was started with.
	g.saveSettings()
	cfg := g.skirmishConfigForStart(mapName)
	request, err := skirmishBattleRequest(g.opts, g.cs, cfg, headlessScenarioSkirmish, nil, newBattleSeedSource(g.opts))
	if err != nil {
		reportRetailMessageError(g.showRetailMessage(err.Error()))
		return
	}
	g.beginFreshBattleLoad(mapName, modeMenuSkirmish, request, nil)
	// The request above is the sole owner of constructor selection and seeds;
	// the loading worker only invokes the shared authoritative seam [08
	// R-ENTRY-01 §1–§2].
}

// loadRetailSavePath is the explicit production save-file seam. It is called
// on the render thread by a host/UI integration that already selected a path;
// no file-picker policy is invented here. The session package prepares all
// authoritative state detached, and this method commits only after battle
// presentation composition has also succeeded [08 R-SAVE-02 §11–§12].
func (g *gameShell) loadRetailSavePath(path string) error {
	if g == nil || g.cs == nil || g.cs.fs == nil {
		return fmt.Errorf("nanolathe: retail save load requires mounted content")
	}
	sim, crt := seedsFor(g.opts)
	// A restored non-campaign battle sizes its unit pool from the configured
	// `[Preferences] UnitLimit`, as a fresh skirmish does [05 R-SHARE-01 §7].
	loaded, err := session.LoadRetailSavePath(path, session.RetailLoadDeps{
		FS: g.cs.fs, SimSeed: sim, CRTSeed: crt, UnitLimit: g.setup.UnitLimit,
	})
	if err != nil {
		return err
	}
	if loaded.Route == session.RetailLoadRouteCampaignContinuation {
		return g.applyRetailContinuation(loaded.Continuation)
	}
	if loaded.Battle == nil || loaded.Battle.Session == nil || loaded.Battle.Image == nil {
		return fmt.Errorf("nanolathe: retail save load returned no battle candidate")
	}
	sess := loaded.Battle.Session
	var campaign *campaignSelection
	if sess.Mission != nil && sess.Mission.Type == mission.TypeCampaign {
		side, known := sess.SideForOwner(int(sess.LocalOwner))
		if !known {
			return fmt.Errorf("nanolathe: restored campaign has no local player side")
		}
		selection, err := g.resolveCampaignSelection(sess.Mission.CampaignPath, sess.Mission.CampaignIndex, side, sess.Mission.Difficulty)
		if err != nil {
			return err
		}
		campaign = &selection
	}
	if g.audioOwner != nil {
		sess.Audio = g.audioOwner
	}
	battle, err := composeBattleEntryDetached(sess, sess.Catalog, g.cs, g, &loaded.Battle.Image.Camera)
	if err != nil {
		return err
	}
	// A restored save adopts on the render thread with no loader goroutine,
	// so the remaster runs inline here and the restore blocks on it. The cache
	// makes that a file read for any map loaded before; a cold cache costs the
	// same seconds a fresh load of the map would, once (DESIGN_GPU_RENDERER
	// §14.4 "When"). It is handed over through pendingDetail exactly as the
	// loading screen's goroutine hands its result to commitBattleCandidate.
	g.pendingDetail = detailArtFor(g.opts, g.cs, sess.World, nil)
	// Retail's battle-restoration dispatcher runs as part of the staging
	// above and, as its first step, carries the save's own `Summary.maxunits`
	// into the process-wide configured unit-limit word — never into the
	// battle just restored, whose pool was already sized from that word as it
	// stood before the restore [08 R-ENTRY-01 §6][08 R-SESS-01 §9]. That
	// configured word is this application's `g.setup.UnitLimit`
	// (internal/session/composition.go's sessionUnitLimit names it), so the
	// carry is the one write below, not a session change.
	g.applyRestoredUnitLimit(loaded.Battle.Image)
	// `LOADGAME`'s `LOAD` reaches the battle through the loading transition, so
	// the restored battle gets the same second-half resize a fresh one does:
	// the window follows `DisplaymodeWidth`/`Height` before the HUD opens
	// [07 "The loading screen"][07 R-FE-01 §8].
	g.applyDisplayMode(clPtr)
	// The only mutation of the active battle/frontend/client state occurs here,
	// after both authoritative and presentation candidates are complete.
	if campaign != nil {
		g.installCampaignSelection(*campaign)
	}
	g.importedRetailBattle = true
	g.commitBattleCandidate(battle)
	clPtr.PrepareBattlePresentation()
	battle.beginBattleArrival(g.opts, clPtr, true)
	return nil
}

// applyRestoredUnitLimit is the one carry retail's battle-restoration
// dispatcher performs into the configured unit-limit word: store the save's
// `Summary.maxunits`, unclamped, but only when the save's Summary account
// carried the item at all — a save without the item leaves the configured
// word untouched [08 R-SESS-01 §9]. The clamp `[Preferences] UnitLimit`
// receives is a start-up read only and is deliberately not repeated here
// [08 R-SKIR-01 §6]; a later skirmish battle entry copies this word verbatim
// into its own session limit.
//
// Presence is what the gate below tests, not a nonzero value:
// save.Summary.HasMaxUnits records whether the item was in the account at all,
// so a save that stores zero carries its zero through and a save that omits the
// item changes nothing. Retail's writer only ever records the start-up-clamped
// configured word (20..500), so a stock save never stores a zero here — that
// case is a fidelity seam, not a path a retail bank reaches.
//
// The word carried in is the configured one; the battle just restored keeps the
// pool it was given, which was sized from that word as it stood before the
// restore (see loadRetailSavePath's RetailLoadDeps.UnitLimit above)
// [08 R-ENTRY-01 §6] [08 R-SESS-01 §9].
func (g *gameShell) applyRestoredUnitLimit(image *save.BattleImage) {
	if g == nil || image == nil || !image.Summary.HasMaxUnits {
		return
	}
	g.setup.UnitLimit = int(image.Summary.MaxUnits)
}

func (g *gameShell) beginFreshBattleLoad(mapName string, back shellMode, request freshBattleRequest, after func(*session.Session)) {
	g.importedRetailBattle = false
	// A fresh loading transition stops ordinary frontend voices immediately.
	// Save restoration defers the matching stop until its committed candidate.
	g.stopOrdinaryAudio()
	g.teardownBattle(clPtr)
	g.bindFrontendClient(clPtr)
	state := newLoadingState(mapName)
	request.value.Progress = state.report
	g.loading = state
	g.loadingReturn = back
	g.openMenu(modeLoading)
	// The loading transition runs at 640x480, not at the chosen display mode.
	// Its first half forces the logical size to 640x480 and, when the window
	// differs, moves the window and re-creates the presentation surface and the
	// offscreen — before the loading background is installed. The resize to
	// `DisplaymodeWidth`/`Height` is the transition's *second* half, taken once
	// the load thread has signalled completion and before the in-game HUD
	// opens; stepLoading is that half [07 "The loading screen"][07 R-FE-02 §2].
	// The authored loading picture is a 640x480 image blitted whole at (0,0)
	// and is never scaled.
	g.applyDisplaySize(clPtr, retailScreenW, retailScreenH)
	go func() {
		authoritative, err := composeAuthoritativeBattle(request)
		if err == nil && after != nil {
			after(authoritative.Session)
		}
		// The load-time remaster runs here, on the loader goroutine, after the
		// session composes and before the battle is adopted, and reports through
		// the same progress callback so the terrain bar keeps moving
		// (DESIGN_GPU_RENDERER §14.4 "When"). A failed load has no world to
		// remaster; the family still reaches 100 so the bar is not left short.
		var detail *client.DetailArt
		if err == nil && authoritative.Session != nil {
			detail = detailArtFor(g.opts, g.cs, authoritative.Session.World, state.report)
		} else {
			state.report(familyDetailArt, 100)
		}
		state.done <- loadResult{sess: authoritative.Session, err: err, detail: detail}
	}()
}

// stepLoading advances the flash on retail's repaint cadence and adopts the
// finished session, or reports the failure the way the screen it was reached
// from reports any other start error.
func (g *gameShell) stepLoading(delta float64) {
	l := g.loading
	if l == nil {
		g.openMenu(g.loadingReturn)
		return
	}
	if l.remaster.Load() != nil {
		l.remasterElapsed += delta
	} else {
		l.remasterElapsed = 0
	}
	for l.repaint += delta; l.repaint >= retailLoadRepaintSeconds; l.repaint -= retailLoadRepaintSeconds {
		l.advanceFlash()
	}
	select {
	case res := <-l.done:
		returnMode := g.loadingReturn
		g.loading = nil
		if res.err != nil {
			g.openMenu(returnMode)
			reportRetailMessageError(g.showRetailMessage(res.err.Error()))
			return
		}
		// The transition's second half: the completed load compares
		// `DisplaymodeWidth`/`Height` to the current window size and, when they
		// differ, moves the window, re-selects the mode and re-creates the
		// offscreen at the battle size, then opens the in-game HUD
		// [07 "The loading screen"]. A failed load stays on 640x480, where the
		// screen it returns to belongs.
		g.applyDisplayMode(clPtr)
		// The remaster's art belongs to the world this load composed; the
		// candidate picks it up at the one render-thread adoption point
		// (commitBattleCandidate), which is also where the terrain reaches the
		// client (DESIGN_GPU_RENDERER §14.3).
		g.pendingDetail = res.detail
		if err := g.enterBattle(res.sess, res.sess.Catalog); err != nil {
			g.loadingReturn = returnMode
			g.openMenu(returnMode)
			g.bindFrontendClient(clPtr)
			reportRetailMessageError(g.showRetailMessage(err.Error()))
		} else {
			clPtr.PrepareBattlePresentation()
		}
	default:
	}
}

func (g *gameShell) drawLoadingScreen(c *client.Client) {
	l := g.loading
	if l == nil || g.assets == nil {
		return
	}
	if bg := g.assets.loading; bg != nil {
		c.UIBlitPCX(bg, 0, 0)
	}
	// The map line comes before the rows, and a campaign mission draws none
	// [07 "The loading screen"].
	if l.mapName != "" {
		title := fmt.Sprintf("%s: %s", "Map", l.mapName)
		width := g.retailTextWidth(title)
		screenW, screenH := c.Size()
		y := int(math.Trunc(float64(screenH) - float64(g.retailTextHeight())*1.5))
		g.drawRetailString(c, title, screenW/2-width/2, y, -1, g.guiColor(retailLoadTitleColor))
	}
	lightbar := g.retailLightBarFrame()
	for i := range retailLoadBars {
		percent := int(l.percent[i].Load())
		if percent < 0 {
			percent = 0
		}
		if percent > 100 {
			percent = 100
		}
		row := retailLoadBars[i]
		// The row's percentage selects one semantic color, which is shared by its
		// label and fill [07 "The loading screen"].
		fill := g.guiColor(retailLoadWorkingColor)
		if percent >= 100 {
			fill = g.guiColor(retailLoadDoneColor)
		}
		// Retail's order within a row is label, fill, grille. The label is at
		// x=0x5a and the bar at x=0xcd, so they never overlap, but keep the
		// order anyway.
		g.drawRetailStringLit(c, row.label, retailLoadLabelX, row.y, -1, fill, l.flash[i])
		// left..left+percent*7/2 inclusive, top..top+20 inclusive.
		c.UIFillRect(retailLoadBarX, row.y, percent*7/2+1, retailLoadBarBottom+1, fill)
		if lightbar != nil {
			blitRetailFrame(c, lightbar, retailLoadBarX, row.y)
		}
	}
	g.drawRemasterProgress(c)
}

// retailLightBarFrame is the common LIGHTBAR entry's frame 0: a 351x21 metal
// grille whose slots are transparent, so the filled part of the bar shows
// through it. The frame carries authored offsets of (19, -27). The
// loading-screen blit path subtracts frame offsets from the pen, so the
// offsets are zeroed before stamping or the grille would miss its bar.
// Nanolathe's gadget blit ignores GAF offsets already, which lands in the same
// place [fmt gaf][07 "The loading screen"].
func (g *gameShell) retailLightBarFrame() *formats.GAFFrame {
	if g == nil || g.assets == nil || g.assets.common == nil {
		return nil
	}
	e, ok := g.assets.common.Find("LIGHTBAR")
	if !ok || len(e.Frames) == 0 {
		return nil
	}
	return e.Frames[0].Frame
}
